# Generated by Django 5.2.6 on 2025-11-25 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('start', '0002_category_body_car_category_color_category_engine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('age', models.IntegerField(verbose_name='age')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='phone')),
                ('category', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='start.category')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
    ]
