# Generated by Django 5.2.6 on 2025-11-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('age', models.IntegerField(verbose_name='age')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='phone')),
                ('mail', models.CharField(blank=True, max_length=20, null=True, verbose_name='mail')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
    ]
