# Generated by Django 5.2.6 on 2025-11-04 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0002_category_body_car_category_color_category_engine'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='id',
        ),
        migrations.AddField(
            model_name='students',
            name='category',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student', serialize=False, to='start.category'),
        ),
    ]
