# Generated by Django 5.2.6 on 2025-10-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='body_car',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='body_car'),
        ),
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='color'),
        ),
        migrations.AddField(
            model_name='category',
            name='engine',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='engine'),
        ),
    ]
